---
permalink: online-help/concept-constituent-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: A página Constituinte volume/Explorador de desempenho fornece informações detalhadas sobre o desempenho para o componente FlexGroup selecionado. 
---
= Página do Explorador de volume/desempenho do constituinte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Constituinte volume/Explorador de desempenho fornece informações detalhadas sobre o desempenho para o componente FlexGroup selecionado.

A página Constituent volume/Performance Explorer permite que você acompanhe e compare o desempenho constituinte durante um período de tempo específico, o que ajuda na solução de problemas e ajuste fino do desempenho de um volume FlexGroup e seus volumes constituintes.

Utilizando a funcionalidade Ver e comparar, pode comparar o desempenho deste volume constituinte com:

* o agregado em que reside este volume constituinte
* A VM de armazenamento em que reside este volume constituinte
* O volume FlexGroup ao qual o volume constituinte pertence
* outros volumes que estão no mesmo agregado


A página Constituent volume/Performance Explorer permite que você:

* Veja os problemas relacionados ao limite e seus detalhes
* Acompanhe e compare os dados de desempenho dos componentes
* Investigue e solucione problemas relacionados ao limite
* Investigue e solucione problemas de desempenho


[NOTE]
====
Para volumes de proteção de dados (DP), somente os valores de contador para tráfego gerado pelo usuário são exibidos.

====