---
permalink: online-help/concept-managing-performance-service-levels.html 
sidebar: sidebar 
keywords:  
summary: Um nível de serviço de performance permite definir os objetivos de desempenho e storage de um workload. Você pode atribuir um nível de Serviço de Performance a uma carga de trabalho ao criar inicialmente a carga de trabalho ou depois editar a carga de trabalho. 
---
= Gerenciando níveis de serviço de performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um nível de serviço de performance permite definir os objetivos de desempenho e storage de um workload. Você pode atribuir um nível de Serviço de Performance a uma carga de trabalho ao criar inicialmente a carga de trabalho ou depois editar a carga de trabalho.

O gerenciamento e o monitoramento de recursos de storage são baseados nos objetivos de nível de serviço (SLOs). Os SLOs são definidos por contratos de nível de serviço baseados no desempenho e na capacidade exigidos. No Gerenciador Unificado, os SLOs referem-se às definições de PSL dos aplicativos que estão sendo executados no storage NetApp. Os serviços de storage são diferenciados com base no desempenho e na utilização dos recursos subjacentes. Um PSL é uma descrição dos objetivos do serviço de storage. Um PSL permite que o provedor de storage especifique os objetivos de desempenho e capacidade para a carga de trabalho.

O Unified Manager fornece algumas políticas enlatadas que não podem ser alteradas. Esses níveis de serviço de performance predefinidos são: Performance, performance e valor extremos. As PSLs de performance, performance e valor extremas são aplicáveis à maioria dos workloads de storage comuns em um data center. O Unified Manager também oferece três PSLs para aplicativos de banco de dados: Extreme for Database Logs, Extreme for Database Shared Data e Extreme for Database Data. Estes são PSLs de alto desempenho que suportam IOPS em expansão e são apropriados para aplicativos de banco de dados com a maior demanda de taxa de transferência. Se essas PSLs predefinidas não atenderem aos seus requisitos, você poderá criar novas PSLs para atender às suas necessidades.

Você pode acessar as PSLs na página *políticas* > *níveis de Serviço de desempenho* e usando as APIs do provedor de armazenamento. Gerenciar workloads de storage atribuindo PSLs a eles é conveniente, pois você não precisa gerenciar individualmente os workloads de storage. Quaisquer modificações também podem ser gerenciadas reatribuindo outro PSL em vez de gerenciá-los individualmente.

Não é possível modificar um PSL definido pelo sistema ou que está atualmente atribuído a uma carga de trabalho. Não é possível excluir um PSL atribuído a uma carga de trabalho ou se for o único PSL disponível.

A página níveis de Serviço de desempenho lista as políticas PSL disponíveis e permite que você as adicione, edite e exclua. Esta página exibe as seguintes informações:

[cols="2*"]
|===
| Campo | Descrição 


 a| 
Nome
 a| 
Nome do nível de Serviço de desempenho.



 a| 
Tipo
 a| 
Se a política é definida pelo sistema ou definida pelo usuário.



 a| 
IOPS esperado
 a| 
Número mínimo de IOPS que um aplicativo deve executar em um LUN ou compartilhamento de arquivos. IOPS esperado especifica o mínimo esperado alocado, com base no tamanho alocado do objeto de storage.



 a| 
IOPS de pico
 a| 
Número máximo de IOPS que um aplicativo pode executar em um LUN ou compartilhamento de arquivos. IOPS de pico especifica o máximo possível alocado, com base no tamanho alocado do objeto de armazenamento ou no tamanho usado do objeto de armazenamento.

IOPS de pico são baseados em uma política de alocação. A política de alocação é alocada-espaço ou espaço usado. Quando a política de alocação é definida como espaço alocado, o IOPS de pico é calculado com base no tamanho do objeto de storage. Quando a política de alocação é definida como espaço usado, o IOPS de pico é calculado com base na quantidade de dados armazenados no objeto de storage, levando em consideração as eficiências de storage. Por padrão, a política de alocação é definida como espaço usado.



 a| 
IOPS mínimo absoluto
 a| 
O IOPS mínimo absoluto é usado como uma substituição, quando o IOPS esperado é menor do que esse valor. Os valores padrão das PSLs definidas pelo sistema são os seguintes:

* Desempenho extremo: Se o IOPS esperado > 6144/TB, o IOPS mínimo absoluto é 1000
* Desempenho: Se o IOPS esperado for superior a 2048/TB e inferior a 6144/TB, o IOPS mínimo absoluto é 500
* Valor: Se IOPS esperado > 128/TB e inferior a 2048/TB, então IOPS mínimo absoluto é 75


Os valores padrão das PSLs de banco de dados definidas pelo sistema são os seguintes:

* Extreme for Database Logs: Se IOPS esperado > 22528, então IOPS mínimo absoluto é 4000
* Extremo para dados compartilhados de banco de dados: Se IOPS esperado > 16384, então IOPS mínimo absoluto é 2000
* Extremo para dados de banco de dados: Se o IOPS esperado > 12288, o IOPS mínimo absoluto é 2000


O valor mais alto do IOPS mínimo absoluto para PSLs personalizadas pode ser de no máximo 75000. O valor mais baixo é calculado da seguinte forma:

1000 ms/latência esperada



 a| 
Latência esperada
 a| 
Latência esperada para IOPS do storage em milissegundos por operação (ms/op).



 a| 
Capacidade
 a| 
Capacidade total disponível e usada nos clusters.



 a| 
Workloads
 a| 
Número de cargas de trabalho de armazenamento que foram atribuídas ao PSL.

|===
Para obter informações sobre como o IOPS de pico e os IOPs esperados ajudam a alcançar desempenho diferenciado consistente em clusters do ONTAP, consulte o seguinte artigo da KB:

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["O que é orçamento de desempenho?"]

Observe que se as cargas de trabalho excederem o valor de latência esperado por 30% do tempo durante a hora anterior, o Unified Manager gerará um dos seguintes eventos para notificá-lo de um possível problema de desempenho: ""limite de latência de volume de carga de trabalho violado conforme definido pela Política de nível de Serviço de Performance" ou ""latência de carga de trabalho LUN violada conforme definido pela Política de limite de nível de Serviço de desempenho". Você pode querer analisar a carga de trabalho para ver o que pode estar causando os valores de latência mais altos.

A tabela a seguir fornece informações sobre as PSLs definidas pelo sistema:

[cols="6*"]
|===
| Nível de Serviço de desempenho | Descrição e caso de uso | Latência esperada (ms/op) | IOPS de pico | IOPS esperado | IOPS mínimo absoluto 


 a| 
Performance extrema
 a| 
Fornece taxa de transferência extremamente alta a uma latência muito baixa

Ideal para aplicações sensíveis à latência
 a| 
1
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
Desempenho
 a| 
Fornece alta taxa de transferência com baixa latência

Ideal para bancos de dados e aplicações virtualizadas
 a| 
2
 a| 
4096
 a| 
2048
 a| 
500



 a| 
Valor
 a| 
Fornece alta capacidade de armazenamento e latência moderada

Ideal para aplicativos de alta capacidade, como e-mail, conteúdo da Web, compartilhamentos de arquivos e destinos de backup
 a| 
17
 a| 
512
 a| 
128
 a| 
75



 a| 
Extremo para Registros de banco de dados
 a| 
Fornece taxa de transferência máxima com a menor latência.

Ideal para aplicações de base de dados que suportam registos de bases de dados. Este PSL fornece o throughput mais alto porque os logs do banco de dados são extremamente bursty e o Registro está constantemente em demanda.
 a| 
1
 a| 
45056
 a| 
22528
 a| 
4000



 a| 
Extremo para dados compartilhados de banco de dados
 a| 
Fornece taxa de transferência muito alta com a menor latência.

Ideal para dados de aplicativos de banco de dados que são armazenados em um armazenamento de dados comum, mas são compartilhados entre bancos de dados.
 a| 
1
 a| 
32768
 a| 
16384
 a| 
2000



 a| 
Extremo para dados de banco de dados
 a| 
Fornece alta taxa de transferência com a menor latência.

Ideal para dados de aplicativos de banco de dados, como informações de tabela de banco de dados e metadados.
 a| 
1
 a| 
24576
 a| 
12288
 a| 
2000

|===