---
permalink: online-help/reference-performance-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'A visualização desempenho: Todos os agregados exibe uma visão geral dos eventos de performance, dados e informações de configuração de cada agregado monitorado por uma instância do Unified Manager. Essa página permite monitorar a performance de agregados e solucionar problemas de performance e eventos de limite.' 
---
= Performance: Visualização de todos os agregados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização desempenho: Todos os agregados exibe uma visão geral dos eventos de performance, dados e informações de configuração de cada agregado monitorado por uma instância do Unified Manager. Essa página permite monitorar a performance de agregados e solucionar problemas de performance e eventos de limite.

Por padrão, os objetos nas páginas de visualização são classificados com base na criticidade do evento. Os objetos com eventos críticos são listados primeiro e os objetos com eventos de aviso são listados em segundo lugar. Isso fornece uma indicação visual imediata dos problemas que devem ser resolvidos.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

Você pode atribuir políticas de limite de desempenho ou limpar políticas de limite de qualquer objeto nas páginas de inventário de objetos usando os botões *atribuir política de limite de desempenho* e *Limpar política de limite de desempenho*.

[NOTE]
====
Agregados de raiz não são exibidos nesta página.

====
xref:reference-aggregate-performance-fields.adoc[Agregar campos de desempenho]Consulte para obter descrições de todos os campos nesta página.
