---
permalink: online-help/reference-health-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'A exibição Saúde: Todos os agregados exibe informações sobre os agregados que são monitorados e permite exibir e modificar as configurações de limite.' 
---
= Saúde: Vista de todos os agregados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A exibição Saúde: Todos os agregados exibe informações sobre os agregados que são monitorados e permite exibir e modificar as configurações de limite.

Por padrão, os objetos nas páginas de visualização são classificados com base na criticidade do evento. Os objetos com eventos críticos são listados primeiro e os objetos com eventos de aviso são listados em segundo lugar. Isso fornece uma indicação visual imediata dos problemas que devem ser resolvidos. Cada agregado na grade de agregados tem links para o Gerenciador de sistemas do ONTAP. Este link redireciona você para ver a mesma relação de proteção no Gerenciador de sistemas do ONTAP.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

Você pode personalizar as configurações de limite de capacidade para um ou mais agregados usando o botão *Edit Threshold*.

xref:reference-aggregate-health-fields.adoc[Agregar campos de saúde]Consulte para obter descrições de todos os campos nesta página.
