---
permalink: online-help/reference-qtree-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: A página limites do Qtree permite configurar valores de limite de capacidade global para qtrees monitorados. Os eventos são gerados para uma qtree somente quando uma cota Qtree ou uma cota padrão tiver sido definida na qtree. Os eventos não são gerados se o espaço definido em uma cota de usuário ou cota de grupo tiver excedido o limite. 
---
= Página limites Qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página limites do Qtree permite configurar valores de limite de capacidade global para qtrees monitorados. Os eventos são gerados para uma qtree somente quando uma cota Qtree ou uma cota padrão tiver sido definida na qtree. Os eventos não são gerados se o espaço definido em uma cota de usuário ou cota de grupo tiver excedido o limite.

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Os eventos são gerados quando um limite é violado. Você pode tomar ações corretivas para tais eventos.



== Área de capacidade

A área capacidade permite definir as seguintes condições de limite de capacidade de qtree.

* *Espaço quase cheio*
+
Especifica a porcentagem em que uma qtree é considerada quase cheia:

+
** Valor padrão: 80 por cento
+
O valor para este limiar deve ser inferior ao valor para o limiar Qtree Full.

** Evento gerado: Qtree quase cheio
** Gravidade do evento: Aviso


* *Espaço cheio*
+
Especifica a porcentagem em que uma qtree é considerada cheia:

+
** Valor padrão: 90 por cento
** Evento gerado: Qtree Full
** Gravidade do evento: Erro



