---
permalink: online-help/reference-health-all-svms-view.html 
sidebar: sidebar 
keywords:  
summary: 'A exibição integridade: Todas as VMs de armazenamento permite exibir informações detalhadas sobre as máquinas virtuais de armazenamento (SVMs) que você está monitorando.' 
---
= Integridade: Exibição de todas as VMs de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização integridade: Todas as VMs de armazenamento permite visualizar informações detalhadas sobre as máquinas virtuais de armazenamento (SVMs) que você está monitorando.

Por padrão, os objetos nas páginas de visualização são classificados com base na criticidade do evento. Os objetos com eventos críticos são listados primeiro e os objetos com eventos de aviso são listados em segundo lugar. Isso fornece uma indicação visual imediata dos problemas que devem ser resolvidos. Cada VM de storage na grade de VMs de storage tem links para o Gerenciador de sistemas do ONTAP. Este link redireciona você para ver a mesma relação de proteção no Gerenciador de sistemas do ONTAP.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

Você pode associar um SVM a uma anotação predefinida usando o botão *Annotate*.

xref:reference-svm-health-fields.adoc[Campos de saúde da SVM]Consulte para obter descrições de todos os campos nesta página.
