---
permalink: online-help/reference-health-all-nodes-view.html 
sidebar: sidebar 
keywords:  
summary: 'A visualização integridade: Todos os nós permite exibir informações detalhadas sobre os nós em todos os clusters gerenciados pelo Unified Manager.' 
---
= Integridade: Exibição de todos os nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização integridade: Todos os nós permite exibir informações detalhadas sobre os nós em todos os clusters gerenciados pelo Unified Manager.

Por padrão, os objetos nas páginas de visualização são classificados com base na criticidade do evento. Os objetos com eventos críticos são listados primeiro e os objetos com eventos de aviso são listados em segundo lugar. Isso fornece uma indicação visual imediata dos problemas que devem ser resolvidos. Cada nó na grade de nós tem links para o Gerenciador de sistema do ONTAP. Este link redireciona você para ver a mesma relação de proteção no Gerenciador de sistemas do ONTAP.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

No menu *relatórios*, a opção *Relatório de inventário de hardware* é fornecida quando o Unified Manager e os clusters que ele está gerenciando são instalados em um site sem conetividade de rede externa. Esse botão gera um `.csv` arquivo que contém uma lista completa de informações de cluster e nó, como números de modelo de hardware e números de série, tipos e contagens de disco, licenças instaladas e muito mais. Essa funcionalidade de relatórios é útil para a renovação de contratos em sites seguros que não estão conetados à plataforma NetAppactive IQ.

xref:reference-node-health-fields.adoc[Campos de integridade do nó]Consulte para obter descrições de todos os campos nesta página.
