---
permalink: online-help/reference-capacity-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'A visualização capacidade: Todos os agregados permite visualizar informações sobre a capacidade e a utilização de agregados em todos os clusters. Essas informações permitem entender possíveis riscos de capacidade e também visualizar a capacidade configurada, usada e não utilizada dos agregados.' 
---
= Capacidade: Visualização de todos os agregados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização capacidade: Todos os agregados permite visualizar informações sobre a capacidade e a utilização de agregados em todos os clusters. Essas informações permitem entender possíveis riscos de capacidade e também visualizar a capacidade configurada, usada e não utilizada dos agregados.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

xref:reference-aggregate-capacity-fields.adoc[Agregar campos de capacidade]Consulte para obter descrições de todos os campos nesta página.
