---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: 'A visualização capacidade: Todos os clusters permite visualizar informações resumidas sobre capacidade de storage e utilização em todos os clusters. Essas informações ajudam você a entender possíveis riscos de capacidade e a tomar as medidas apropriadas para rebalancear os workloads.' 
---
= Capacidade: Visualização de todos os clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização capacidade: Todos os clusters permite visualizar informações resumidas sobre capacidade de storage e utilização em todos os clusters. Essas informações ajudam você a entender possíveis riscos de capacidade e a tomar as medidas apropriadas para rebalancear os workloads.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

xref:reference-cluster-capacity-fields.adoc[Campos de capacidade do cluster]Consulte para obter descrições de todos os campos nesta página.
