---
permalink: online-help/reference-protection-storage-virtual-machine-associations-page.html 
sidebar: sidebar 
keywords:  
summary: A página colegas do SVM permite visualizar os pares de VM de storage existentes entre a VM de storage de origem e destino e criar uma nova VM de storage para uso por aplicações de parceiros a fim de criar relacionamentos SnapMirror e SnapVault. 
---
= Página colegas SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página colegas do SVM permite visualizar os pares de VM de storage existentes entre a VM de storage de origem e destino e criar uma nova VM de storage para uso por aplicações de parceiros a fim de criar relacionamentos SnapMirror e SnapVault.



== Botões de comando

Os botões de comando permitem executar as seguintes tarefas:

* *Criar*
+
Abre a página criar pares de máquina virtual de armazenamento.

* *Excluir*
+
Permite eliminar os pares de VM de armazenamento selecionados.





== Lista de pares de VM de storage

A lista SVM peers (peers) exibe em uma tabela as associações de VM de armazenamento de origem e destino que foram criadas e o tipo de relação de proteção permitido para cada associação.

* *Source Storage Virtual Machine*
+
Exibe o nome da SVM de origem.

* *Cluster de origem*
+
Exibe o nome do cluster de origem.

* *Destination Storage Virtual Machine*
+
Exibe o nome do SVM de destino.

* *Cluster de destino*
+
Exibe o nome do cluster de destino.

* *Tipo*
+
Exibe o tipo de relação de proteção. Os tipos de relacionamento são SnapMirror ou SnapVault.


