---
permalink: online-help/reference-capacity-all-qtrees-view.html 
sidebar: sidebar 
keywords:  
summary: 'A visualização capacidade: Todas as Qtrees permite visualizar informações sobre a capacidade e utilização de qtrees em todos os clusters. Essas informações permitem que você entenda possíveis riscos de capacidade e também visualize a porcentagem de disco configurado e usado e o número de arquivos.' 
---
= Capacidade: Vista de todas as Qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização capacidade: Todas as Qtrees permite visualizar informações sobre a capacidade e utilização de qtrees em todos os clusters. Essas informações permitem que você entenda possíveis riscos de capacidade e também visualize a porcentagem de disco configurado e usado e o número de arquivos.

Por padrão, os objetos nas páginas de visualização são classificados com base na criticidade do evento. Os objetos com eventos críticos são listados primeiro e os objetos com eventos de aviso são listados em segundo lugar. Isso fornece uma indicação visual imediata dos problemas que devem ser resolvidos.

Os controles ao longo da parte superior da página permitem selecionar uma exibição específica (para integridade, desempenho, capacidade e assim por diante), realizar pesquisas para localizar objetos específicos, criar e aplicar filtros para restringir a lista de dados exibidos, adicionar/remover/reordenar colunas na página e exportar os dados na página para um `.csv` arquivo , ou `.xlsx` . `.pdf` Depois de personalizar a página, você pode salvar os resultados como uma visualização personalizada e, em seguida, agendar um relatório desses dados para ser gerado e enviado por e-mail regularmente.

Você pode personalizar as configurações de limite de capacidade para um ou mais qtrees usando o botão *Edit Threshold*.

xref:reference-qtree-capacity-fields.adoc[Campos de capacidade Qtree]Consulte para obter descrições de todos os campos nesta página.
