---
permalink: online-help/reference-configuring-ontap-cluster.html 
sidebar: sidebar 
keywords: NetApp Snapshot backup for Windows,configuring ONTAP cluster 
summary: Antes de configurar o backup e a restauração do Active IQ Unified Manager para Snapshot para Windows, você deve executar algumas pré-configurações para a máquina host ONTAP e Windows. 
---
= Configurando o cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar o backup e a restauração do Active IQ Unified Manager para Snapshot para Windows, você deve executar algumas pré-configurações para a máquina host ONTAP e Windows.

Você pode configurar o cluster do ONTAP usando o prompt de comando ou a interface do usuário do Gerenciador do sistema. A configuração do cluster ONTAP envolve a configuração de LIFs de dados para estarem disponíveis para serem atribuídos como LIFs iSCSI à VM de armazenamento. A próxima etapa é configurar uma VM de armazenamento habilitada para iSCSI usando a interface do usuário do System Manager. Você precisará configurar uma rota de rede estática para essa VM de armazenamento para controlar como os LIFs usam a rede para o tráfego de saída.

[NOTE]
====
Você deve ter um volume dedicado e um LUN para configuração de backup. O volume selecionado deve incluir apenas um LUN. O tamanho do LUN deve ser pelo menos o dobro do tamanho de dados esperado para ser Tratado pelo Active IQ Unified Manager.

====
Você precisa executar a seguinte configuração:

. Configure uma VM de armazenamento habilitada para iSCSI ou use uma VM de armazenamento existente que tenha a mesma configuração.
. Configure uma rota de rede para a VM de armazenamento configurada.
. Configure um volume de capacidade adequada e um único LUN no interior, garantindo que o volume seja dedicado apenas a este LUN.
. Configure um grupo de iniciadores na VM de armazenamento.
. Configurar um conjunto de portas.
. Integre o igrop com o portset.
. Mapeie o LUN para o grupo.

