---
permalink: online-help/task-viewing-the-svm-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: 'Na exibição integridade: Todas as VMs de armazenamento, você pode monitorar seu inventário de máquinas virtuais de armazenamento (SVMs). Você pode usar a página Storage VM / Health details para exibir informações detalhadas sobre SVMs que são monitoradas.' 
---
= Exibindo a lista e os detalhes da VM de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na visualização integridade: Todas as VMs de armazenamento, você pode monitorar seu inventário de máquinas virtuais de armazenamento (SVMs). Você pode usar a página Storage VM / Health details para exibir informações detalhadas sobre SVMs que são monitoradas.



== Antes de começar

Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.



== Sobre esta tarefa

É possível visualizar os detalhes do SVM, como capacidade, eficiência e configuração de um SVM. Você também pode exibir informações sobre os dispositivos relacionados e alertas relacionados para esse SVM.



== Passos

. No painel de navegação esquerdo, clique em *Storage* > *Storage VMs*.
. Escolha uma das seguintes maneiras de exibir os detalhes do SVM:
+
** Para exibir informações sobre a integridade de todos os SVMs em todos os clusters, no menu Exibir, selecione integridade: Exibição de todas as VMs de armazenamento.
** Para exibir os detalhes completos, clique no nome da VM de armazenamento.
+
Você também pode visualizar os detalhes completos clicando em *Exibir detalhes* na caixa de diálogo Detalhes mínimos.



. Visualize os objetos relacionados ao SVM clicando em *Exibir relacionado* na caixa de diálogo Detalhes mínimos.

