---
permalink: online-help/task-rediscovering-clusters.html 
sidebar: sidebar 
keywords: rediscover cluster,refresh cluster 
summary: É possível redescobrir manualmente um cluster a partir da página Configuração do cluster para obter as informações mais recentes sobre a integridade, o status do monitoramento e o status do desempenho do cluster. 
---
= Redescobrir clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível redescobrir manualmente um cluster a partir da página Configuração do cluster para obter as informações mais recentes sobre a integridade, o status do monitoramento e o status do desempenho do cluster.



== Sobre esta tarefa

Você pode redescobrir manualmente um cluster quando quiser atualizar o cluster, como aumentando o tamanho de um agregado quando houver espaço insuficiente, e deseja que o Unified Manager descubra as alterações feitas.

Quando o Unified Manager é emparelhado com o OnCommand Workflow Automation (WFA), o emparelhamento aciona a reaquisição dos dados armazenados em cache pelo WFA.



== Passos

. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração do cluster*.
. Na página *Configuração de cluster*, clique em *redescobrir*.
+
O Unified Manager redescobre o cluster selecionado e exibe o status de integridade e desempenho mais recente.


