---
permalink: online-help/task-configuring-windows-host-machine.html 
sidebar: sidebar 
keywords: NetApp Snapshot backup for Windows,configuring Windows host machine 
summary: 'Você precisa configurar sua máquina host do Windows, na qual o Active IQ Unified Manager está instalado, para se preparar para o backup do NetApp Snapshot. Para iniciar o iniciador iSCSI da Microsoft em uma máquina host do Windows, digite "iscsi" na barra de pesquisa e clique em Iniciador iSCSI.' 
---
= Configurando a máquina host do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa configurar sua máquina host do Windows, na qual o Active IQ Unified Manager está instalado, para se preparar para o backup do NetApp Snapshot. Para iniciar o iniciador iSCSI da Microsoft em uma máquina host do Windows, digite "iscsi" na barra de pesquisa e clique em *Iniciador iSCSI*.



== Antes de começar

Você deve limpar todas as configurações anteriores na máquina host.



== Sobre esta tarefa

Se você estiver tentando iniciar o iniciador iSCSI em uma nova instalação do Windows, será solicitado a confirmação e, na confirmação, a caixa de diálogo Propriedades iSCSI será exibida. Se for uma instalação do Windows existente, a caixa de diálogo Propriedades iSCSI será exibida com um destino inativo ou tentando se conetar. Portanto, você precisará garantir que todas as configurações anteriores no host do Windows sejam removidas.



== Passos

. Limpe todas as configurações anteriores na máquina host.
. Descubra o portal de destino.
. Conete-se ao portal de destino.
. Conecte-se usando multipath ao portal de destino.
. Descubra os dois LIFs.
. Descubra o LUN configurado na máquina Windows como um dispositivo.
. Configure o LUN descoberto como uma nova unidade de volume no Windows.

