---
permalink: online-help/task-restoring-data-using-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: 'Você pode restaurar arquivos, diretórios ou um volume inteiro sobrescritos ou excluídos de uma cópia Snapshot usando o recurso de restauração na exibição integridade: Todos os volumes.' 
---
= Restaurar dados usando a exibição Saúde: Todos os volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode restaurar arquivos, diretórios ou um volume inteiro sobrescritos ou excluídos de uma cópia Snapshot usando o recurso de restauração na exibição integridade: Todos os volumes.



== Antes de começar

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.



== Sobre esta tarefa

Não é possível restaurar fluxos de ficheiros NTFS.

A opção de restauração não está disponível quando:

* O ID do volume é desconhecido: Por exemplo, quando você tem uma relação entre clusters e o cluster de destino ainda não foi descoberto.
* O volume é configurado para replicação síncrona do SnapMirror.




== Passos

. Na exibição *Saúde: Todos os volumes*, selecione um volume do qual você deseja restaurar os dados.
. Na barra de ferramentas, clique em *Restaurar*.
+
A caixa de diálogo Restaurar é exibida. A caixa de diálogo é modificada para ter um layout de duas colunas para exibir e selecionar vários arquivos. Mas você só pode selecionar 10 Registros de cada vez.

. Selecione o volume e a cópia Snapshot a partir da qual você deseja restaurar dados, se diferente do padrão.
. Selecione os itens que deseja restaurar.
+
Você pode restaurar todo o volume ou especificar pastas e arquivos que deseja restaurar.

. Selecione o local para o qual deseja restaurar os itens selecionados; *localização original* ou *localização alternativa*.
. Clique em *Restaurar*.
+
O processo de restauração é iniciado.


