---
permalink: online-help/task-adding-clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: Você pode adicionar um cluster ao Active IQ Unified Manager para que você possa monitorar o cluster. Isso inclui a capacidade de obter informações de cluster, como integridade, capacidade, desempenho e configuração do cluster, para que você possa encontrar e resolver quaisquer problemas que possam ocorrer. 
---
= Adição de clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar um cluster ao Active IQ Unified Manager para que você possa monitorar o cluster. Isso inclui a capacidade de obter informações de cluster, como integridade, capacidade, desempenho e configuração do cluster, para que você possa encontrar e resolver quaisquer problemas que possam ocorrer.



== Antes de começar

* Você deve ter a função Administrador do aplicativo ou a função Administrador do armazenamento.
* Você deve ter o nome do host ou o endereço IP de gerenciamento de cluster (IPv4 ou IPv6) para o cluster.
+
Ao usar o nome do host, ele deve ser resolvido para o endereço IP de gerenciamento de cluster para o LIF de gerenciamento de cluster. Se você usar um LIF de gerenciamento de nós, a operação falhará.

* Tem de ter o nome de utilizador e a palavra-passe para aceder ao cluster.
+
Essa conta deve ter a função _admin_ com acesso ao aplicativo definido como _ontapi_, _ssh_ e _http_.

* Você deve saber o número da porta para se conetar ao cluster usando o protocolo HTTPS (normalmente a porta 443).
* O cluster deve estar executando o software ONTAP versão 9,1 ou superior.
* Você precisa ter espaço adequado no servidor do Unified Manager. Você é impedido de adicionar um cluster ao servidor quando mais de 90% de espaço já estiver consumido.
* Você tem os certificados necessários. São necessários dois tipos de certificados:
+
*Certificados de servidor*: Usados para Registro. É necessário um certificado válido para adicionar um cluster. Se o certificado do servidor expirar, você deverá regenerá-lo e reiniciar o Unified Manager para que os serviços sejam registrados automaticamente novamente. Para obter informações sobre a geração de certificados, consulte o artigo da base de conhecimento (KB): https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["Como renovar um certificado SSL no ONTAP 9"]

+
*Certificados de cliente*: Usado para autenticação. É necessário um certificado válido para adicionar um cluster. Não é possível adicionar um cluster ao Unified Manager com um certificado expirado e, se o certificado de cliente já tiver expirado, deve ser regenerado antes de adicionar o cluster. No entanto, se esse certificado expirar para um cluster que já foi adicionado e está sendo usado pelo Unified Manager, as mensagens EMS continuarão funcionando com o certificado expirado. Não é necessário regenerar o certificado de cliente.



[NOTE]
====
Você pode adicionar clusters que estão por trás de um NAT/firewall usando o endereço IP NAT do Unified Manager. Qualquer sistema de automação do fluxo de trabalho conetado ou SnapProtect também deve estar atrás do NAT/firewall, e as chamadas da API SnapProtect devem usar o endereço IP NAT para identificar o cluster.

====


== Sobre esta tarefa

* Cada cluster em uma configuração do MetroCluster deve ser adicionado separadamente.
* Uma única instância do Unified Manager pode dar suporte a um número específico de nós. Se você precisar monitorar um ambiente que exceda a contagem de nós com suporte, instale uma instância adicional do Unified Manager para monitorar alguns dos clusters.
* Você pode monitorar um único cluster por duas instâncias do Unified Manager desde que tenha configurado um segundo LIF de gerenciamento de cluster no cluster para que cada instância do Unified Manager se conete por meio de um LIF diferente.




== Passos

. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração do cluster*.
. Na página *Configuração de cluster*, clique em *Adicionar*.
. Na caixa de diálogo *Adicionar cluster*, especifique os valores conforme necessário e clique em *Enviar*.
. Na caixa de diálogo *autorizar Host*, clique em *Exibir certificado* para exibir as informações do certificado sobre o cluster.
. Clique em *Sim*.
+
O Unified Manager verifica o certificado somente quando o cluster é adicionado inicialmente. O Unified Manager não verifica o certificado de cada chamada de API para o ONTAP.





== Resultados

Depois que todos os objetos de um novo cluster forem descobertos (cerca de 15 minutos), o Unified Manager começa a coletar dados históricos de desempenho dos 15 dias anteriores. Essas estatísticas são coletadas usando a funcionalidade de coleta de continuidade de dados. Esse recurso fornece mais de duas semanas de informações de desempenho para um cluster imediatamente após ser adicionado. Após a conclusão do ciclo de coleta de continuidade de dados, os dados de desempenho do cluster em tempo real são coletados, por padrão, a cada cinco minutos.

[NOTE]
====
Como a coleta de dados de desempenho de 15 dias é intensiva em CPU, sugere-se que você alterne a adição de novos clusters para que as pesquisas de coleta de continuidade de dados não sejam executadas em muitos clusters ao mesmo tempo. Além disso, se você reiniciar o Unified Manager durante o período de coleta de continuidade de dados, a coleta será interrompida e você verá lacunas nos gráficos de desempenho para o período de tempo em falta.

====
[TIP]
====
Se receber uma mensagem de erro que não pode adicionar o cluster, verifique se existem os seguintes problemas:

* Se os relógios nos dois sistemas não estiverem sincronizados e a data de início do certificado HTTPS do Unified Manager for posterior à data no cluster. Você deve garantir que os relógios são sincronizados usando NTP ou um serviço similar.
* Se o cluster tiver atingido o número máximo de destinos de notificação EMS, o endereço do Unified Manager não poderá ser adicionado. Por predefinição, apenas podem ser definidos 20 destinos de notificação EMS no cluster.


====