---
settings:
  name: Active IQ Unified Manager 9.9
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  langs: pt-br,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos do Active IQ Unified Manager 9,9
    url: "/index.html"
  - title: Notas de lançamento
    url: "/release-notes.html"
  - title: Comece agora
    entries:
    - title: Instalação rápida do VMware vSphere
      url: "/qsg-vapp.html"
    - title: Instalação rápida para Linux
      url: "/qsg-linux.html"
    - title: Instalação rápida para Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Avisos legais
    url: "/legal-notices.html"
