---
permalink: qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Guia de início rápido para Unified Manager na plataforma Linux. 
---
= Instruções de início rápido para instalações do Windows
:allow-uri-read: 


[role="lead"]
Você pode baixar o pacote de instalação e instalar o Unified Manager para monitorar e solucionar problemas de capacidade, disponibilidade, performance e proteção de storage de dados.



== Requisitos do sistema

* Sistemas operacionais: Microsoft Windows Server 2016 e edições Standard e Datacenter de 2019 64 bits. Os seguintes idiomas são suportados:
+
** Inglês
** Japonês
** Chinês simplificado


* RAM: 12 GB
* CPU: Total de 9572 MHz
* Espaço livre em disco: 100 GB de espaço em disco para o diretório de instalação, 50 GB de espaço em disco para o diretório de dados MySQL


Para obter os requisitos detalhados do sistema, consulte link:./install-windows/concept-requirements-for-installing-unified-manager.html["Requisitos para instalar o Unified Manager"]e link:http://mysupport.netapp.com/matrix["Matriz de interoperabilidade"].



== A instalar o Active IQ Unified Manager



=== Baixe o instalador

. Baixe o `ActiveIQUnifiedManager-<version>.exe` pacote de instalação.
. Copie o arquivo de instalação para um diretório no sistema de destino.




=== Instale o Unified Manager

Para instalar o Unified Manager, certifique-se de que tem o Microsoft .NET 4,5.2 ou uma versão posterior instalada. Como parte do processo de instalação, o Unified Manager instala outros pacotes de terceiros, conforme necessário. Para obter mais informações sobre os pacotes de software dependentes, consulte o link:./install-windows/reference-windows-software-and-installation-requirements.html["Requisitos de software e instalação do Windows"].

. Inicie sessão no Windows utilizando a conta de administrador local predefinida.
. No diretório em que você baixou o arquivo de instalação, clique com o botão direito do Mouse e execute o arquivo executável do Unified Manager (.exe) como administrador.
. Quando solicitado, insira o nome de usuário e a senha para criar o usuário de manutenção do Unified Manager.
. No assistente conexão de banco de dados, insira a senha raiz do MySQL.
. Siga as instruções restantes para concluir a instalação.
. Clique em *Finish* no final da instalação e a IU da Web do Unified Manager será exibida.

