---
permalink: api-automation/reference-recommendations-to-use-the-apis.html 
sidebar: sidebar 
keywords:  
summary: Ao usar as APIs no Active IQ Unified Manager, você deve seguir certas práticas recomendadas. 
---
= Recomendações para o uso das APIs para Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao usar as APIs no Active IQ Unified Manager, você deve seguir certas práticas recomendadas.

* Todo o tipo de conteúdo de resposta deve estar no seguinte formato para uma execução válida:


[listing]
----
application/json
----
* O número da versão da API não está relacionado com o número da versão do produto. Você deve usar a versão mais recente da API disponível para sua instância do Unified Manager. Para obter mais informações sobre as versões da API do Unified Manager, consulte a seção "versão da API REST no Active IQ Unified Manager".
* Ao atualizar valores de array usando uma API do Unified Manager, você deve atualizar toda a cadeia de valores. Não é possível anexar valores a uma matriz. Você só pode substituir um array existente.
* Você pode usar operadores de filtro, como pipe (|) e Wild card (*) para todos os parâmetros de consulta, exceto para valores duplos, por exemplo, IOPS e desempenho nas APIs de métricas. Evite consultar objetos usando uma combinação de carateres Wild card (*) e pipe (|) dos operadores de filtro. Ele pode recuperar um número incorreto de objetos.
* Observe que a `GET` solicitação (todas) para qualquer API retorna um máximo de 1000 Registros. Mesmo que você execute a consulta definindo o `max_records` parâmetro para um valor maior que 1000, apenas 1000 Registros serão retornados.
* Para executar funções administrativas, é recomendável usar a IU do Unified Manager.

