---
permalink: reporting/generaltask-um-rest-apis-that-can-be-used-for-reporting.html 
sidebar: sidebar 
keywords:  
summary: Você pode usar as APIS REST para ajudar a gerenciar clusters visualizando as informações de integridade, capacidade, desempenho e segurança capturadas pelo Unified Manager. 
---
= APIs REST do Unified Manager que podem ser usadas para geração de relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar as APIS REST para ajudar a gerenciar clusters visualizando as informações de integridade, capacidade, desempenho e segurança capturadas pelo Unified Manager.

As APIs REST são expostas por meio da página da Web do Swagger. Você pode acessar a página da Web do Swagger para exibir a documentação da API REST do Unified Manager, bem como emitir manualmente uma chamada de API. Na IU da Web do Unified Manager, na barra de menus, clique no botão *Ajuda* e selecione *Documentação da API*. Para obter informações sobre as APIs REST do Unified Manager, link:../api-automation/concept-getting-started-with-getting-started-with-um-apis.html["Introdução ao Active IQ Unified Manager"]consulte .

Você deve ter a função Operador, Administrador de armazenamento ou Administrador de aplicativo para acessar as APIS REST.
