---
permalink: health-checker/task-restoring-a-snapshot-backup.html 
sidebar: sidebar 
keywords: restore,linux 
summary: Se ocorrer perda de dados ou corrupção de dados, você poderá restaurar o Unified Manager para o estado estável anterior com perda mínima de dados. Você pode restaurar o banco de dados Snapshot do Unified Manager para um sistema operacional local ou remoto usando o console de manutenção do Unified Manager. 
---
= Restaurar um backup Snapshot para Linux e Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se ocorrer perda de dados ou corrupção de dados, você poderá restaurar o Unified Manager para o estado estável anterior com perda mínima de dados. Você pode restaurar o banco de dados Snapshot do Unified Manager para um sistema operacional local ou remoto usando o console de manutenção do Unified Manager.



== Antes de começar

* Você deve ter as credenciais de usuário raiz para o host Linux e o Privileges administrativo para a máquina host Windows na qual o Unified Manager está instalado.
* Você deve ter uma ID de usuário e senha autorizados para fazer login no console de manutenção do servidor do Unified Manager.




== Sobre esta tarefa

O recurso de restauração é específico da plataforma e específico da versão. Você pode restaurar um backup do Unified Manager somente na mesma versão do Unified Manager.



== Passos

. Conete-se ao endereço IP ou ao nome de domínio totalmente qualificado do sistema Unified Manager.


[cols="2*"]
|===
| * Linux* | Shell seguro 


 a| 
*Windows*
 a| 
Shell de energia

|===
. Inicie sessão no sistema com o nome e a palavra-passe do utilizador de manutenção (umadmin).
. Digite o comando `maintenance_console` e pressione Enter.
. No console de manutenção *Menu Principal*, digite o número da opção *Backup Restore*.
. Digite o número para *Backup e Restauração usando Instantâneo do NetApp*.
+
Se você estiver executando uma restauração em um novo servidor, após a instalação do Unified Manager, não inicie a IU nem configure clusters, usuários ou configurações de autenticação quando a instalação for concluída. Digite o número para *Configurar cópia de segurança do instantâneo do NetApp* e configure as definições de cópia de segurança do instantâneo conforme foram configuradas no sistema original.

. Digite o número para *Restaurar usando Instantâneo do NetApp*.
. Selecione o arquivo de backup instantâneo que você deseja restaurar e pressione *Enter*.
. Depois que o processo de restauração for concluído, faça login na interface de usuário do Unified Manager.




== Depois de terminar

Depois de restaurar o backup, se o servidor do Workflow Automation não funcionar, execute as seguintes etapas:

. No servidor do Workflow Automation, altere o endereço IP do servidor do Unified Manager para apontar para a máquina mais recente.
. No servidor do Unified Manager, redefina a senha do banco de dados se a aquisição falhar na etapa 1.

