---
permalink: install-vapp/task-deploying-the-unified-manager-virtual-appliance-vapp.html 
sidebar: sidebar 
keywords:  
summary: Depois de fazer o download do arquivo de instalação, você implanta o Unified Manager como um dispositivo virtual. Use o vSphere Web Client para implantar o dispositivo virtual em um servidor ESXi. Quando você implementa o dispositivo virtual, uma máquina virtual é criada. 
---
= Implantando o dispositivo virtual do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de fazer o download do arquivo de instalação, você implanta o Unified Manager como um dispositivo virtual. Use o vSphere Web Client para implantar o dispositivo virtual em um servidor ESXi. Quando você implementa o dispositivo virtual, uma máquina virtual é criada.



== Antes de começar

Você deve analisar os requisitos do sistema. Faça as alterações necessárias antes de implantar o dispositivo virtual do Unified Manager.

xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Requisitos de infraestrutura virtual]

xref:reference-vmware-software-and-installation-requirements.adoc[Requisitos de software e instalação da VMware]

Se utilizar o DHCP (Dynamic Host Configuration Protocol), certifique-se de que o servidor DHCP está disponível e que as configurações do adaptador de rede DHCP e máquina virtual (VM) estão corretas. O DHCP é configurado por padrão.

Se você usar uma configuração de rede estática, verifique se o endereço IP não está duplicado na mesma sub-rede e se as entradas apropriadas do servidor DNS foram configuradas.

Obtenha as seguintes informações antes de implantar o dispositivo virtual:

* Credenciais para acessar o VMware vCenter Server e o vSphere Web Client
* Endereço IP do servidor ESXi no qual você está implantando o dispositivo virtual do Unified Manager
* Detalhes sobre o data center, como disponibilidade de espaço de storage
* Se você não estiver usando DHCP, obtenha os endereços IPv4 ou IPv6 para os dispositivos de rede aos quais você está planejando se conetar:
+
** Nome de domínio totalmente qualificado (FQDN) do host
** Endereço IP do host
** Máscara de rede
** Endereço IP do gateway padrão
** Endereços DNS primário e secundário
** Pesquisar domínios






== Sobre esta tarefa

A partir do Unified Manager 9,8, o VMware Tools foi substituído por Open VM Tools  `open-vm-tools`). Você não precisa instalar o VMware Tools como parte do processo de instalação porque `open-vm-tools` está incluído no pacote de instalação do Unified Manager.

Quando o dispositivo virtual é implantado, um certificado autoassinado exclusivo para acesso HTTPS é gerado. Ao acessar a IU da Web do Unified Manager, você pode ver um aviso do navegador sobre certificados não confiáveis.

O VMware High Availability para o dispositivo virtual do Unified Manager é compatível.



== Passos

. No vSphere Client, clique em *File* > *Deploy OVF Template*.
. Conclua o assistente *Deploy OVF Template* para implantar o dispositivo virtual do Unified Manager.
+
Na página Configuração de rede:

+
** Deixe todos os campos em branco ao usar endereçamento DHCP e IPv4.
** Marque a caixa ""Ativar endereçamento IPv6 automático"" e deixe todos os outros campos em branco ao usar endereçamento DHCP e IPv6.
** Se você quiser usar uma configuração de rede estática, você pode preencher os campos nesta página e essas configurações serão aplicadas durante a implantação. Certifique-se de que o endereço IP é exclusivo para o host no qual ele é implantado, que ele ainda não está em uso e que ele tem uma entrada DNS válida.


. Depois que o dispositivo virtual do Unified Manager for implantado no servidor ESXi, ligue a VM clicando com o botão direito do Mouse na VM e, em seguida, selecionando *ligar*.
+
[NOTE]
====
Se a operação de ativação falhar devido a recursos insuficientes, adicione recursos e tente novamente a instalação.

====
. Clique na guia *Console*.
+
O processo de inicialização inicial leva alguns minutos para ser concluído.

. Para configurar seu fuso horário, insira sua área geográfica e sua cidade ou região conforme solicitado na janela VM *Console*.
+
Todas as informações de data exibidas usam o fuso horário configurado para o Unified Manager, independentemente da configuração de fuso horário nos dispositivos gerenciados. Se os seus sistemas de armazenamento e o servidor de gestão estiverem configurados com o mesmo servidor NTP, referem-se ao mesmo instante a tempo, mesmo que pareçam diferentes. Por exemplo, se você criar uma cópia Snapshot usando um dispositivo configurado usando um fuso horário diferente do servidor de gerenciamento, o carimbo de hora será a hora do servidor de gerenciamento.

. Se não houver serviços DHCP disponíveis ou se houver um erro nos detalhes da configuração de rede estática, selecione uma das seguintes opções:
+
[cols="2*"]
|===
| Se você usar... | Então faça isso... 


 a| 
DHCP
 a| 
Selecione *Repetir DHCP*. Se pretende utilizar o DHCP, deve certificar-se de que está configurado corretamente.

Se você usar uma rede habilitada para DHCP, as entradas do FQDN e do servidor DNS serão dadas automaticamente ao dispositivo virtual. Se o DHCP não estiver configurado corretamente com o DNS, o nome do host "'UnifiedManager'" será atribuído automaticamente e associado ao certificado de segurança. Se não tiver configurado uma rede com DHCP, deverá introduzir manualmente as informações de configuração da rede.



 a| 
Uma configuração de rede estática
 a| 
.. Selecione *Introduza os detalhes para a configuração de rede estática*.
+
O processo de configuração leva alguns minutos para ser concluído.

.. Confirme os valores que introduziu e selecione *Y*.


|===
. No prompt, insira um nome de usuário de manutenção e clique em *Enter*.
+
O nome do usuário de manutenção deve começar com uma letra de a-z, seguida de qualquer combinação de -, a-z ou 0-9.

. No prompt, digite uma senha e clique em *Enter*.
+
O console da VM exibe o URL da IU da Web do Unified Manager.





== Depois de terminar

Você pode acessar a IU da Web para executar a configuração inicial do Unified Manager, conforme descrito em link:../config/task-using-the-maintenance-console.html["Utilizar a consola de manutenção"].
