---
permalink: install-windows/reference-windows-software-and-installation-requirements.html 
sidebar: sidebar 
keywords:  
summary: Para a instalação bem-sucedida do Unified Manager no Windows, você deve garantir que o sistema no qual o Unified Manager está sendo instalado atenda aos requisitos de software. 
---
= Requisitos de software e instalação do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Para a instalação bem-sucedida do Unified Manager no Windows, você deve garantir que o sistema no qual o Unified Manager está sendo instalado atenda aos requisitos de software.



== Software do sistema operativo

O Unified Manager é compatível com o sistema operacional Windows de 64 bits para os seguintes idiomas:

* Inglês
* Japonês
* Chinês simplificado


Você pode instalar o Unified Manager nas seguintes edições do Windows:

* Microsoft Windows Server 2016 Standard e Datacenter Edition
* Microsoft Windows Server 2019 Standard e Datacenter Edition


Observe que o Windows Server 2012 não é suportado como era em versões anteriores. Consulte a Matriz de interoperabilidade para obter a lista completa e mais atual de versões suportadas do Windows.

http://mysupport.netapp.com/matrix["mysupport.NetApp.com/matrix"]

O servidor deve ser dedicado à execução do Unified Manager. Nenhum outro aplicativo deve ser instalado no servidor.



== Software de terceiros

Os seguintes pacotes de terceiros são empacotados com o Unified Manager. Se esses pacotes de terceiros não estiverem instalados no sistema, o Unified Manager os instalará como parte da instalação.

* Microsoft Visual C& n.o 43;& n.o 43; 2015 Redistributable package versão 14.26.28720.3
* Microsoft Visual C& n.o 43;& n.o 43; Redistributable Packages for Visual Studio 2013 versão 12.0.40660
* MySQL Community Edition versão 8.0.21
+
[NOTE]
====
O instalador do Unified Manager foi restrito para suportar apenas até o MySQL Community Edition 8,0.21, devido a um problema de interoperabilidade. Você *não deve* atualizar o MySQL para uma versão maior que 8,0.21.

====
* Python 3,6.x
* OpenJDK versão 11.0.9
* p7zip versão 18,05 ou posterior


[NOTE]
====
A partir do Unified Manager 9,5, o OpenJDK é fornecido no pacote de instalação do Unified Manager e instalado automaticamente. O Oracle Java não é suportado a partir do Unified Manager 9,5.

====
Se o MySQL estiver pré-instalado, você deve garantir que:

* Ele está usando a porta padrão.
* Os bancos de dados de amostra não estão instalados.
* O nome do serviço é "MYSQL8".


O Unified Manager é implantado em um servidor web WildFly. O WildFly17 é empacotado e configurado com o Unified Manager.

[NOTE]
====
Você deve encerrar uma instância em execução do Unified Manager antes de atualizar qualquer software de terceiros. Depois que a instalação de software de terceiros estiver concluída, você poderá reiniciar o Unified Manager.

====


== Requisitos de instalação

* O Microsoft .NET 4,5.2, ou superior, deve ser instalado.
* O `temp` diretório deve ser configurado com 2 GB de espaço em disco para extrair os arquivos de instalação. Para verificar se o diretório foi criado, execute o seguinte comando na interface de linha de comando: `echo %temp%`
* Você deve reservar 2 GB de espaço em disco na unidade do Windows para armazenar em cache os arquivos MSI do Unified Manager.
* O Microsoft Windows Server no qual você deseja instalar o Unified Manager deve ser configurado com um nome de domínio totalmente qualificado (FQDN), de modo que `ping` as respostas ao nome do host e FQDN sejam bem-sucedidas.
* Você deve desativar o serviço de publicação na Web mundial do Microsoft IIS e garantir que as portas 80 e 443 são gratuitas.
* Você deve certificar-se de que a configuração do Host de sessão de Área de trabalho Remota para "'Compatibilidade RDS do Windows Installer'" esteja desativada durante a instalação.
* A porta UDP 514 deve ser livre e não deve ser usada por nenhum outro serviço.


[NOTE]
====
O programa de instalação do Unified Manager configura as seguintes exclusões no Windows Defender:

* Diretório de dados do Unified Manager
* Diretório de instalação do Unified Manager
* Diretório de dados MySQL


Se o servidor tiver um antivírus diferente instalado, você deve configurar essas exclusões manualmente.

====