---
section: config
title: Executar tarefas de configuração e administrativas
entries:
- title: Configurando o Active IQ Unified Manager
  url: "/config/concept-configuring-unified-manager.html"
  entries:
  - title: Descrição geral da sequência de configuração
    url: "/config/concept-overview-of-the-configuration-sequence.html"
  - title: Acessando a IU da Web do Unified Manager
    url: "/config/task-accessing-oncommand-unified-manager-web-ui.html"
  - title: Executando a configuração inicial da IU da Web do Unified Manager
    url: "/config/task-performing-the-initial-setup-of-the-unified-manager-web-ui.html"
  - title: Adição de clusters
    url: "/config/task-adding-clusters.html"
  - title: Configurando o Unified Manager para enviar notificações de alerta
    url: "/config/task-configuring-unified-manager-to-send-alert-notifications.html"
    entries:
    - title: Configurar definições de notificação de eventos
      url: "/config/task-configuring-event-notification-settings.html"
    - title: Ativar autenticação remota
      url: "/config/task-enabling-remote-authentication.html"
    - title: Desativando grupos aninhados da autenticação remota
      url: "/config/task-disabling-nested-groups-from-remote-authentication.html"
    - title: Adicionando servidores de autenticação
      url: "/config/task-adding-authentication-servers.html"
    - title: Testando a configuração dos servidores de autenticação
      url: "/config/task-testing-the-configuration-of-authentication-servers-um-6-0.html"
    - title: Adicionando usuários
      url: "/config/task-adding-users.html"
    - title: Adicionar alertas
      url: "/config/task-adding-alerts.html"
  - title: Eventos EMS que são adicionados automaticamente ao Unified Manager
    url: "/config/reference-ems-events-that-are-added-automatically-to-unified-manager.html"
  - title: Subscrever eventos ONTAP EMS
    url: "/config/task-subscribing-to-ontap-ems-events.html"
  - title: Gerenciando configurações de autenticação SAML
    url: "/config/concept-managing-saml-authentication-settings-um.html"
    entries:
    - title: Requisitos do provedor de identidade
      url: "/config/reference-identity-provider-requirements-um.html"
    - title: Habilitando a autenticação SAML
      url: "/config/task-enabling-saml-authentication-um.html"
  - title: Alterar a palavra-passe do utilizador local
    url: "/config/task-changing-the-local-user-password.html"
  - title: Definir o tempo limite de inatividade da sessão
    url: "/config/task-setting-the-session-inactivity-timeout.html"
  - title: Alterando o nome do host do Unified Manager
    url: "/config/concept-changing-the-unified-manager-host-name.html"
    entries:
    - title: Alterando o nome do host do dispositivo virtual do Unified Manager
      url: "/config/task-changing-the-unified-manager-host-name-on-vmware.html"
      entries:
      - title: Gerando um certificado de segurança HTTPS
        url: "/config/task-generating-an-https-security-certificate-ocf.html"
      - title: Reiniciando a máquina virtual do Unified Manager
        url: "/config/task-restarting-the-unified-manager-virtual-machine.html"
    - title: Alteração do nome de host do Unified Manager em sistemas Linux
      url: "/config/task-changing-the-unified-manager-host-name-on-rhel-or-centos.html"
  - title: Ativar e desativar o gerenciamento de armazenamento baseado em políticas
    url: "/config/task-enabling-and-disabling-policy-based-storage-management.html"
- title: Configuração do backup do Unified Manager
  url: "/config/concept-configuring-um-backup.html"
- title: Utilizar a consola de manutenção
  url: "/config/task-using-the-maintenance-console.html"
  entries:
  - title: Que funcionalidade o console de manutenção fornece
    url: "/config/concept-what-functionality-the-maintenance-console-provides.html"
  - title: O que o utilizador de manutenção faz
    url: "/config/concept-what-the-maintenance-user-does.html"
  - title: Capacidades do utilizador de diagnóstico
    url: "/config/concept-what-the-diagnostic-user-does.html"
  - title: Aceder à consola de manutenção
    url: "/config/task-accessing-the-maintenance-console.html"
  - title: Acessando o console de manutenção usando o console vSphere VM
    url: "/config/task-accessing-the-maintenance-console-using-vsphere.html"
  - title: Menus da consola de manutenção
    url: "/config/concept-maintenance-console-menu.html"
    entries:
    - title: Menu Network Configuration (Configuração da rede)
      url: "/config/reference-network-configuration-menu.html"
    - title: Menu System Configuration (Configuração do sistema)
      url: "/config/reference-system-configuration-menu.html"
    - title: Menu suporte e Diagnóstico
      url: "/config/reference-support-and-diagnostics-menu.html"
    - title: Opções de menu adicionais
      url: "/config/reference-additional-menu-options.html"
  - title: Alterar a palavra-passe do utilizador de manutenção no Windows
    url: "/config/task-changing-the-maintenance-user-password-on-windows.html"
  - title: Alterar a senha umadmin em sistemas Linux
    url: "/config/task-changing-the-umadmin-password-on-rhel.html"
  - title: Alterar as portas que o Unified Manager usa para protocolos HTTP e HTTPS
    url: "/config/task-changing-the-ports-um-uses-for-http-and-https-protocols.html"
  - title: Adicionando interfaces de rede
    url: "/config/task-adding-additional-network-interfaces.html"
  - title: Adicionando espaço em disco ao diretório do banco de dados do Unified Manager
    url: "/config/concept-adding-disk-space-to-the-unified-manager-database-directory.html"
    entries:
    - title: Adicionando espaço ao diretório de dados do host Linux
      url: "/config/task-adding-space-to-the-data-directory-of-the-unified-manager-red-hat-enterprise-linux-host.html"
    - title: Adicionando espaço ao disco de dados da máquina virtual VMware
      url: "/config/task-adding-space-to-the-data-disk-of-the-vmware-virtual-machine.html"
    - title: Adicionando espaço à unidade lógica do servidor Microsoft Windows
      url: "/config/task-adding-space-to-the-data-disk-of-the-microsoft-windows-server.html"
