---
permalink: install-linux/task-downloading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Você deve fazer download do arquivo do Unified Manager.zipG no site de suporte da NetApp para instalar o Unified Manager. 
---
= A transferir o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve fazer download do arquivo do Gerenciador Unificado``.zip`` no site de suporte da NetApp para instalar o Gerenciador unificado.



== Antes de começar

Você deve ter credenciais de login para o site de suporte da NetApp.



== Sobre esta tarefa

Faça o download do mesmo pacote de instalação do Unified Manager para os sistemas Red Hat Enterprise Linux e CentOS.



== Passos

. Faça login no site de suporte da NetApp e navegue até a página *Download* do Gerenciador Unificado: https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de suporte da NetApp"]
. Selecione a versão necessária do Unified Manager e aceite o contrato de licença de usuários finais (EULA).
. Faça o download do arquivo do instalador do Unified Manager para Linux e salve o `.zip` arquivo em um diretório no sistema de destino.
+
[NOTE]
====
Certifique-se de baixar a versão correta do arquivo de instalação para o seu sistema Red Hat Enterprise Linux. Com base se você tem o Red Hat Enterprise Linux 7 ou 8 instalado, certifique-se de baixar a versão apropriada do arquivo Unified Manager``.zip``.

====
. Verifique a soma de verificação para garantir que o software foi transferido corretamente.

