---
permalink: install-linux/task-upgrading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Você pode fazer o upgrade do Unified Manager 9,7 ou 9,8 para 9,9 baixando e executando o arquivo de instalação na plataforma Red Hat. 
---
= Atualizando o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer o upgrade do Unified Manager 9,7 ou 9,8 para 9,9 baixando e executando o arquivo de instalação na plataforma Red Hat.



== Antes de começar

* O sistema no qual você está atualizando o Unified Manager deve atender aos requisitos de sistema e software.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Requisitos do sistema de hardware]

+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Requisitos de instalação e software Red Hat e CentOS]

* Você deve instalar ou atualizar para a versão correta do OpenJDK antes de atualizar o Unified Manager.
+
xref:task-upgrading-openjdk-on-linux-ocum.adoc[Atualizando o JRE no Linux]

* O MySQL Community Edition é atualizado automaticamente durante a atualização do Unified Manager. Se a versão instalada do MySQL no seu sistema for anterior à 8,0.25, o processo de atualização do Unified Manager atualizará automaticamente o MySQL para 8,0.25.
+
No entanto, você pode querer atualizar o MySQL para a versão menor mais recente em seu sistema. Antes de atualizar para a próxima versão menor, certifique-se de que a versão base do MySQL no seu sistema é 8,0.25.

* Você precisa ter uma assinatura do Red Hat Enterprise Linux Subscription Manager.
* Para evitar a perda de dados, você deve ter criado um backup do banco de dados do Unified Manager caso haja algum problema durante a atualização. Também é recomendável que você mova o arquivo de backup do `/opt/netapp/data` diretório para um local externo.
* Durante a atualização, você pode ser solicitado a confirmar se deseja manter as configurações padrão anteriores para reter dados de desempenho por 13 meses ou alterá-los para 6 meses. Ao confirmar, os dados históricos de desempenho após 6 meses são purgados.
* Você deve ter concluído todas as operações em execução, pois o Unified Manager não está disponível durante o processo de atualização.




== Passos

. Faça login no servidor Red Hat Enterprise Linux ou CentOS de destino.
. Faça o download do pacote Unified Manager para o servidor.
+
xref:task-downloading-unified-manager.adoc[Download do Unified Manager para Red Hat ou CentOS]

. Navegue até o diretório de destino e expanda o pacote do Unified Manager: `unzip ActiveIQUnifiedManager-<version\>.zip`
+
Os módulos RPM necessários para o Unified Manager são descompactados no diretório de destino.

. Verifique se o seguinte módulo está disponível no diretório: `ls *.rpm`
+
** `netapp-um<version\>.x86_64.rpm`


. Para sistemas que não estejam conetados à Internet ou que não estejam usando os repositórios Red Hat Enterprise Linux, execute as etapas a seguir para determinar se você está faltando nenhum pacote necessário e baixe esses pacotes:
+
.. Veja a lista de pacotes disponíveis e indisponíveis: `yum install netapp-um<version\>.x86_64.rpm --assumeno`
+
Os itens na seção "'Instalando:'" são os pacotes que estão disponíveis no diretório atual, e os itens na seção "'Instalando para dependências:'" são os pacotes que estão faltando no seu sistema.

.. Em um sistema diferente que tenha acesso à Internet, execute o seguinte comando para baixar os pacotes ausentes. `yum install package_name --downloadonly --downloaddir=.`
+
Os pacotes são baixados no diretório especificado como `–downloaddir=.`

+
Como o plug-in "yum-plugin-downloadonly" nem sempre está ativado em sistemas Red Hat Enterprise Linux, você pode precisar habilitar a funcionalidade para baixar um pacote sem instalá-lo:``yum install yum-plugin-downloadonly``

.. Crie um novo diretório no sistema de instalação e copie os pacotes baixados do sistema conetado à Internet.
.. Mude os diretórios para o novo diretório no sistema de instalação e execute o seguinte comando para instalar o MySQL Community Edition, juntamente com suas dependências. `yum install *.rpm`


. Execute o script de pré-instalação para garantir que não há configurações de sistema ou qualquer software instalado que possa entrar em conflito com a atualização: `sudo ./pre_install_check.sh`
+
O script de pré-instalação verifica se o sistema tem uma assinatura válida do Red Hat e se ele tem acesso aos repositórios de software necessários. Se o script identificar quaisquer problemas, você deve corrigir os problemas antes de atualizar o Unified Manager.

. Atualize o Unified Manager usando o seguinte script: `upgrade.sh`
+
Esse script executa automaticamente os módulos RPM, atualizando o software de suporte necessário e os módulos do Unified Manager que são executados neles. Além disso, o script de atualização verifica se há configurações de sistema ou qualquer software instalado que possa entrar em conflito com a atualização. Se o script identificar quaisquer problemas, você deve corrigir os problemas antes de atualizar o Unified Manager.

. Depois que a atualização estiver concluída, role para trás pelas mensagens até que a mensagem exiba um endereço IP ou URL para a IU da Web do Unified Manager, o nome do usuário de manutenção (umadmin) e a senha padrão.
+
A mensagem é semelhante à seguinte:

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----




== Depois de terminar

Insira o endereço IP ou URL especificado em um navegador da Web compatível para iniciar a IU da Web do Unified Manager e, em seguida, faça login usando o mesmo nome de usuário de manutenção (umadmin) e senha definidos anteriormente.
